<?php

/**
 * @file
 * Primary module hooks for Custom Plugin module.
 */

use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;


/**
 * Implementation of hook_views_query_alter
 */
function custom_plugin_views_query_alter(ViewExecutable $view, QueryPluginBase $query): void {

  if (($view->id() === 'content') && ($query->getBaseId() === 'views_query')) {
    $query->addOrderBy('node_field_data', 'status', 'DESC');
    $query->addWhere(0, 'type', 'page');
  }
}
